workflows:
 ios-workflow:
    name: iOS Workflow
    instance_type: mac_pro
    max_build_duration: 120
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"       
        BUNDLE_ID: "com.example.firebaseCrash"      
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      # - name: Set up keychain to be used for codesigning using Codemagic CLI 'keychain' command
      #   script: |
      #     keychain initialize
      # - name: Fetch signing files
      #   script: |
      #     app-store-connect fetch-signing-files $BUNDLE_ID --type IOS_APP_STORE --create
      # - name: Use system default keychain
      #   script: |
      #     keychain add-certificates
      # - name: Set up code signing settings on Xcode project
      #   script: |
      #     xcode-project use-profiles
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
      - name: Flutter build ipa and automatic versioning
        script: |
          flutter build ipa --debug 
    artifacts:
       - /tmp/xcodebuild_logs/*.log
       - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
       - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
