workflows:
 ios-workflow:
    name: iOS Workflow
    instance_type: mac_pro
    max_build_duration: 120
    environment:   
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter packages
        script: |
          cd . && flutter packages pub get
      - name: Install pods
        script: |
          find . -name "Podfile" -execdir pod install \;
          flutter build ios --debug --no-codesign
    artifacts:
#        - /tmp/xcodebuild_logs/*.log
#        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
#        - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
       
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
